"""empty message

Revision ID: 88ff09a62b3c
Revises: 
Create Date: 2019-09-03 20:31:19.005473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ff09a62b3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(precision=2, asdecimal=6), nullable=False),
    sa.Column('longitude', sa.Float(precision=3, asdecimal=6), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('urls', sa.Text(), nullable=False),
    sa.Column('usecode', sa.String(length=20), nullable=True),
    sa.Column('num_bedrooms', sa.Integer(), nullable=True),
    sa.Column('num_bathrooms', sa.Float(precision=2, asdecimal=1), nullable=True),
    sa.Column('house_sqft', sa.Integer(), nullable=True),
    sa.Column('lot_sqft', sa.Integer(), nullable=True),
    sa.Column('zpid', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('modified_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('house_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('address', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=40), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('income', sa.Float(precision=13, asdecimal=2), nullable=True),
    sa.Column('sjsu_affiliated', sa.Boolean(), nullable=True),
    sa.Column('education', sa.Enum('Some High School', 'High School', 'Some College', 'Bachelors Degree', 'Masters Degree', 'Doctorate', 'Unspecified', name='education_levels'), nullable=True),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other', 'Unspecified', name='gender_types'), nullable=True),
    sa.Column('ownership', sa.Enum('Rent', 'Own', 'Other', 'Unspecified', name='ownership_types'), nullable=True),
    sa.Column('housing_method', sa.Enum('House', 'Condominium', 'Apartment', 'Room', 'Shared Room', 'Mobile Home', 'Unspecified', name='housing_types'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('modified_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('predicted_score', sa.Integer(), nullable=True),
    sa.Column('actual_score', sa.Integer(), nullable=True),
    sa.Column('viewed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('modified_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.house_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('users')
    op.drop_table('houses')
    # ### end Alembic commands ###
